### DISCUSSION TITLE
Clean way to override or modify openupgrade modification script

### DISCUSSION THREAD

**Discussion by maximead** [OCA/OpenUpgrade#3231] [Q&A] [answered]
Hi all,

Thank you for developing this. Maybe this would appear as a beginner question (or a Python related question), but anyways... I searched and I don't know what I should do.

I'm trying to get around a 13 -> 14 migration. For some reasons, I do not want a method that is in openupgrade to be run. This in the module account, in post-migration.py, method fill_account_payment_with_no_move .

The easy way is for me to comment the line calling it and call it a day.

However, I do not want this modification to be within this file as it was developed by openupgrade. I want my customization to be separated... I honestly don't know how to do that.

Is there a way by loading a custom module account in another directory to somehow modify the script?

Sorry if it sounds dumb, but... Don't know where to go for help.

Thank you,

**Comment by legalsylvain** [comment, marked as answer]
Hi @maximead.

I think that your need could be done via code management.
- clone ``openupgrade`` project
- fork it
- make custom modifications on your branch and commit.

Then you can use some tools like ``gitaggregate`` to merge all the branches you want. (the OCA one, yours branches, etc...).
https://pypi.org/project/git-aggregator/

```
./src/openupgrade:
  remotes:
    OCA: https://github.com/OCA/OpenUpgrade
    maximead: https://github.com/maximead/OpenUpgrade
  target: OCA 12.0-target
  merges:
    - OCA 12.0
    - maximead YOUR-CUSTOM-BRANCH

```
