### ISSUE TITLE
OpenUpgrade and Travis

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#113]
Hi all,

I had an idea some weeks ago, when I discovered Travis System and I'd like to have your point of view.

I imagined to realize a Travis script that will realize the following things (for a migration to 7 -> 8):
- clone odoo 7.0 branch;
- get openupgrade 8.0 branch;
- for each module with migration analyzed and done;
  - create a 7.0 database and install the module with demo data;
  - launch openupgrade 8.0 and so run the migration script of the module (and all dependencies);

Once the system done, it can be easily ported for next migration (8 -> 9);
- The system can prevent some bug; (for exemple the recent bug we had about views);
- If demo data are present, the coverage will be bigger and we can detect some problems automatically;
- The system can so detect a problem when a people propose some PR about a new module;

@StefanRijnhart, @ all What do you think about that idea ?

Regards.

**Comment by rvalyi** [comment]
Hello @legalsylvain 

That sounds all the rage. However I believe Travis free plans have a max execution time of ~12 minutes and my feeling is that it will not fit. Worth a double check. Also some OCA people are setting up a dedicated runbot system, may be it could be hacked into doing what you want (not on Travis infrastructure then).

Well this is just my hot feeling, it's probably worth a try or more investigation.

**Comment by legalsylvain** [comment]
Hi @rvalyi,
Ok thanks about the information about max execution time. I think that it can fit at the beginning, but maybe not if all modules are done. (That was not the case for 7.0). We have to check that.
And without talking about the infrastructure, what is your point of view about the idea as such ?

thanks.

**Comment by rvalyi** [comment]
@legalsylvain yes, that may be possible with just a few module, not sure. Well the idea itself is great as I said.

**Comment by bwrsandman** [comment]
This completely depends on demo data migration and if these datas are complete and non-iterferal with migration scripts.

It shouldn't be too difficult to do for version 8.0 of OpenUpgrade:

``` yml
language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone https://github.com/${ODOO_REPO}.git ${HOME}/new-version -b ${VERSION} --depth=1

script:
  - ${HOME}/Odoo/openerp_server -d OpenUpgrade -i all --without-demo=False --stop-after-init
  - coverage run ./scripts/migrate.py -d OpenUpgrade
  - ${HOME}/new-version/openerp_server -d OpenUpgrade --stop-after-init | grep ERROR

after_success:
  coveralls
```

Not tested, just quickly typed, the commands and paths are probably different.
