### ISSUE TITLE
Migration Step for Odoo v15 to v16 with docker

### ISSUE THREAD

**Issue by ikus060** [OCA/OpenUpgrade#3846]
Hi there! 

I'm trying to upgrade my Odoo instance from version 15 to version 16 using the Odoo OpenUpgrade tool. However, when running Odoo in a container with the Docker image "odoo:15.0", I can't seem to find the migration step for this version upgrade.

I've looked through the documentation and searched online, but haven't been able to find any information on this specific issue. Can someone please help me figure out how to access the migration step for upgrading from Odoo v15 to v16 when running Odoo in a container with the "odoo:15.0" Docker image?

**Comment by legalsylvain** [comment]
Hi, thanks for your interest in Openupgrade project.

When you want to upgrade from 15.0 to 16.0 you have to use odoo 16.0 + openupgrade 16.0. 
This may not be very clear in the documentation. As I am currently working on it, I will try to clarify this important point.

Once you use the correct version, you have to follow the instruction [and set the openupgrade modules in the addons_path.](https://oca.github.io/OpenUpgrade/migration_details.html)

**Comment by ikus060** [comment]
> When you want to upgrade from 15.0 to 16.0 you have to use odoo 16.0 + openupgrade 16.0.

While it make sens, I have no idea what is the implication of this statement. Do I need to start an additional container with odoo:16.0 

I search for a docker image named "openupgrade" in dockerhub and did not found any. At least none of them looked official.

What would be helpful is an example of how odoo it running then provide the steps with command line to upgrade ?

e.g.: I'm running odoo with the following docker-compose:
```
version: "3.1"
services:
  web:
    image: odoo:15.0
    restart: "always"
    deploy:
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    depends_on:
      - db
    volumes:
      - ./data/addons/:/mnt/extra-addons
      - ./data/conf/:/etc/odoo/
      - ./data/data/:/var/lib/odoo
    environment:
      ODOO_DATABASE_HOST: db
      ODOO_DATABASE_USER: odoo
      ODOO_DATABASE_PASSWORD: odoo
      ODOO_DATABASE_NAME: postgres
    ports:
      - 8069:8069
  db:
    image: postgres:13
    restart: "always"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./db:/var/lib/postgresql/data
```
